### ISSUE TITLE
Изначально создавать плоский мир для работы над новым миром

### ISSUE THREAD

**Issue by John888Tomson** [caiiiycuk/vangers-web#7]
Для того что бы удобнее было начать работу над новым миром лучше подойдёт пустая плоскость с высотой в 0.
И таких заготовок лучше всего иметь всех размеров что может обработать программа.
Может достаточно и не больше чем в 2 раза больше от размера 3 основных миров(фострал, глоркс, некросс), но лучше иметь больше вариантов что могут понадобится чем меньше.

**Comment by Aidoneus** [comment]
Дополню

В world.ini мира в последней секции можно задавать настройки, по которым Сюрмап сгенерирует шумом чистый мир (размер шума, сила шума и т.п.). Было бы клёво дать их покрутить и на их основе новый мир генерировать. Ну и выбор плоскости тоже бы.

Куда-то сюда же – выбор размера мира, она же "длина"-y, степени двойки начиная от 10 (меньше не работают) и заканчивая... а не знаю вот, сколько максимум Сюрмап/игра потянет. Тестировать надо. Каждый следующий вдвое больше предыдущего же.
